[package]
name = "atto"
version = "0.0.1"
authors = ["Dariusz Depta <dariusz.depta@engos.software>"]
description = "atto"
documentation = "https://docs.rs/atto"
repository = "https://github.com/EngosSoftware/atto.git"
license = "MIT"
edition = "2021"