[package]
name = "atto"
version = "0.0.3"
authors = ["senees <code@senees.de>"]
description = "atto"
documentation = "https://docs.rs/atto"
repository = "https://github.com/senees/atto.git"
license = "MIT"
edition = "2021"
